Basic design of the training program
velotio-tech/go-k8s-training pull request #2
Opened 2021-01-20 16:54 UTC by prafull11

2021-01-20 18:09 UTC, madhurtrilio requested changes

2021-01-20 18:09 UTC, madhurtrilio commented on README.md
> +An intense 2 months program for young software engineers with at least 2 years of industry experience. This program will train you to become a cloud native engineer with technologies, like Golang, Ku
don't specify duration as 2 months. We don't want this to be a time bound exercise. The duration would be set according to how well an individual can pick
Don't specify min experience, can specify areas of knowledge like : Person having worked on any backend language, has some virtualization exposure, knows database relations and understands REST API's has an added advantage

2021-01-20 18:09 UTC, madhurtrilio commented on README.md
> +- [Assignments]()
please add [Study Material]()

2021-01-20 18:09 UTC, madhurtrilio commented on README.md
> +- [Assignments]()
please add [Study Material]()

2021-01-28 13:58 UTC, madhurvelotio commented on README.md
> +- [Assignments]()
Is that resolved?

2021-01-28 13:58 UTC, madhurvelotio commented on README.md
> +- [Assignments]()
Is that resolved?

2021-01-29 06:34 UTC, madhurvelotio approved these changes

2021-01-29 06:34 UTC, merged